2023-12-27 13:15:38,834 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2023-12-27 13:15:38,834 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\inspector\AppData\Local\Programs\Python\Python310\lib\site-packages\instabot\bot\bot.py
2023-12-27 13:15:38,834 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2023-12-27 13:15:38,974 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2023-12-27 13:15:38,984 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2023-12-27 13:15:38,984 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2023-12-27 13:15:39,199 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2023-12-27 13:15:39,858 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2023-12-27 13:15:39,986 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [429]>
2023-12-27 13:15:39,995 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2023-12-27 13:15:39,995 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
